apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data-pvc
  namespace: connected-kiln
spec:
  accessModes:
    - ReadWriteOnce # Typically suitable for a single-replica Mosquitto
  resources:
    requests:
      storage: 1Gi # Request 1 Gigabyte of storage (adjust as needed)
  # storageClassName: your-storage-class-name # Uncomment and set if you need a specific StorageClass