# 4-telegraf-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  namespace: connected-kiln
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      securityContext:
        # This is the pod-level securityContext
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
        - name: telegraf
          image: telegraf:latest
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop: [ "ALL" ]
            readOnlyRootFilesystem: false
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: config
              mountPath: /etc/telegraf/
      volumes:
        - name: config
          configMap:
            name: telegraf-config